# config/tags.yaml
drivers:
- name: mb_tcp_1
  type: modbus_tcp
  host: 127.0.0.1
  port: 5020
  poll_interval: 0.5

- name: internal_1
  type: internal
  persistence_file: data/internal_tags.json

tags:
  # Цех 1
- name: Temp_Reactor_1
  path: ''
  source: mb_tcp_1
  address: 4x0010
  type: float32
- name: Pressure_Reactor_1
  path: ''
  source: mb_tcp_1
  address: 4x0012
  type: float32
- name: Valve_Inlet_1
  path: ''
  source: mb_tcp_1
  address: 80
  type: bool
- name: Temp_Mixer_1
  path: ''
  source: mb_tcp_1
  address: 4x0100
  type: float32
- name: Temp_Furnace_1
  path: ''
  source: mb_tcp_1
  address: 4x0200
  type: float32
- name: Temp_Furnace_2
  path: ''
  source: mb_tcp_1
  address: 4x0202
  type: float32
- name: Setpoint_Global
  path: ''
  source: internal
  address: ''
  type: float32
  value: 75.0
- name: Alarm_Active
  path: ''
  source: internal
  address: ''
  type: bool
  value: false
- name: Pump_Status
  path: ''
  source: internal
  address: ''
  type: float32
