---
drivers:
- name: mb_tcp_1
  type: modbus_tcp
  host: 127.0.0.1
  port: 5020
  poll_interval: 0.5

- name: internal_1
  type: internal
  persistence_file: data/my_tags.json    # опционально
  save_interval: 5.0                     # опционально

tags:
  # Внешние теги (Modbus)
- name: Setpoint_Temp
  source: internal
  address: ''
  type: float32
  value: 75.0
- name: Alarm_HighTemp
  source: internal
  address: ''
  type: bool
  value: false
- name: Calculated_Avg
  source: internal
  address: ''
  type: float32
  value: 0.0
- name: Temp
  source: internal
  address: ''
  type: float32
  value: 5.0
- name: Temp_Reactor
  source: internal
  address: ''
  type: float32
  value: 10.6
